Vahapp2/Models/LoanDetails.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vahapp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetails
    {
        public int LoanDetailID { get; set; }
        public int LoanID { get; set; }
        public int UserID { get; set; }
    
        public virtual Loans Loans { get; set; }
        public virtual Users Users { get; set; }
    }
}

Vahapp2/Models/Notifications.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vahapp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotifID { get; set; }
        public string Sapo { get; set; }
        public byte[] SsHash { get; set; }
        public string Otsikko { get; set; }
        public string Viesti { get; set; }
        public string ExtraField { get; set; }
    }
}

Vahapp2/Controllers/LoanDetailsController.cs
using System.Web;
using System.Web.Mvc;
using Vahapp2.Models;
using System.Data.Entity;
using System.Net;
using System.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Mail;
using System.Text;

namespace Vahapp2.Controllers
{
    public class LoanDetailsController : Controller
    {
        private VahappEntities db = new VahappEntities();
        // GET: LoanDetails
        public ActionResult Index()
        {

            var loandetails = db.LoanDetails.Include(a => a.Loans).Include(a => a.Users);

            return View(loandetails.ToList());

        }

        public ActionResult Notifications(int? id)
        {
            
            if (Session["AdminUser"] != null)
            {

                var ld = db.Loans.Find(id);
            var notif = db.Notifications.FirstOrDefault();
            string resultString = Encoding.UTF8.GetString(notif.SsHash);
            MailAddress to = new MailAddress(ld.Users.Email);

            MailAddress from = new MailAddress(notif.Sapo);

            MailMessage email = new MailMessage(from, to);

            email.Subject = notif.Otsikko;
            email.Body = notif.Viesti;
                
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587; 
            smtp.Credentials = new NetworkCredential(notif.Sapo, resultString);
            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtp.EnableSsl = true;
            try
            {
                
                smtp.Send(email);
                    
                return RedirectToAction("Index", "Loans");
            }
            catch (Exception)
            {

                return View("NotifError");
            }
            }
            else return RedirectToAction("login", "home");

        }

        public ActionResult SetNotifications()
        {
            ViewBag.Notif = db.Notifications.FirstOrDefault();
            if (Session["AdminUser"] != null)
            {
                return View();
            }
            else return RedirectToAction("login", "home");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SetNotifications([Bind(Include = "NotifID,Sapo,SsHash,Otsikko,Viesti,ExtraField")] Notifications not)
        {
            byte[] Bytes = Encoding.UTF8.GetBytes(not.ExtraField);
            if (ModelState.IsValid)
            {
                not.SsHash = Bytes;
                not.ExtraField = null;
                var removal = db.Notifications.FirstOrDefault();
                if(removal != null)
                {
                    db.Notifications.Remove(removal);
                }
                
                db.Notifications.Add(not);
                db.SaveChanges();
                return RedirectToAction("Index", "Loans");
            }

            return View();
        }

        public ActionResult DeleteNotifications(int? id)
        {
            Notifications not = db.Notifications.FirstOrDefault();

            if (Session["AdminUser"] != null)
            {
                return View(not);
            }
            else return RedirectToAction("login", "home");
            
            

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteNotifications()
        {
            Notifications not = db.Notifications.FirstOrDefault();
            if (ModelState.IsValid)
            {
                
                
                if (not != null)
                {
                    db.Notifications.Remove(not);
                }

               
                db.SaveChanges();
                return RedirectToAction("Index", "Loans");
            }

            return View();
        }
    }
}

Vahapp2/Views/LoanDetails/DeleteNotifications.cshtml
@model Vahapp2.Models.Notifications

@{
    ViewBag.Title = "DeleteNotifications";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sapo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sapo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SsHash)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.SsHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Otsikko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Otsikko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Viesti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Viesti)
        </dd>

        

        <dd>
            @Html.HiddenFor(model => model.ExtraField)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index","Loans")
        </div>
    }
</div>

Vahapp2/Views/LoanDetails/Notifications.cshtml
@model IEnumerable<Vahapp2.Models.LoanDetails>

@{
    ViewBag.Title = "Notifications";
}

<h2>Notifications</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Loans.LoanID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Users.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Loans.LoanID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Users.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LoanDetailID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LoanDetailID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LoanDetailID })
        </td>
    </tr>
}

</table>

Vahapp2/Views/LoanDetails/SetNotifications.cshtml
@model Vahapp2.Models.Notifications

<p>
    VaHapp2 Uses Gmail to notify expired loans. <br /> You can enter the info in this form. <br />
    Two factor Authentication must be turned on and AppPassword is required.<br />
    You can configure only one notifier settings at the time. If you want to make new settings.<br />
    Just fill in the form and submit and the info will be replaced automatically<br /> and the previous settings will be deleted.
    <br /> By disabling the notifications, notify by email buttons are not available<br /> and notification data is deleted from database.
</p>

@using (Html.BeginForm("SetNotifications", "LoanDetails", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.Label("Sending Email")
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Sapo)
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.Label("Email Subject")
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Otsikko)
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.Label("Message")
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.Viesti)
        </div>
    </div>
    <br />

    <div class="form-group">
        @Html.Label("AppPass")
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.ExtraField)
        </div>
    </div>
    <br />



    @Html.HiddenFor(model => model.SsHash)




    <input type="submit" value="Create" class="btn btn-default" />

}

<div>
    @if (ViewBag.Notif != null)
    {
    <button onclick="location.href='@Url.Action("DeleteNotifications", "LoanDetails")'" class="btn btn-primary">Disable Notifications</button>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}